id: P000562
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS17366
  title: རྒྱལ་མཚན་རྩེ་མོའི་དཔུང་རྒྱན་གཟུངས་དང་ཆ་གསུམ།
  author: ''
  volumes:
    f0946dfec3574baf9db9412a7561e0f1:
      image_group_id: I8LS17374
      title: Volume 1 of rgyal mtshan rtse mo'i dpung rgyan gzungs dang cha gsum/
      volume_number: 1
      total_pages: 454
      base_file: v001.txt
